# Generated by Django 3.2.6 on 2022-12-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pix',
            field=models.ImageField(default='avartar.png', upload_to='profiles/'),
        ),
    ]
