# Generated by Django 3.2.6 on 2022-12-24 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 24, 20, 46, 51, 656307)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 24, 20, 46, 51, 661237)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 24, 20, 46, 51, 656307)),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
