# Generated by Django 3.2.6 on 2022-12-26 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20221226_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 26, 15, 21, 7, 787795)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 26, 15, 21, 7, 792629)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 26, 15, 21, 7, 786892)),
        ),
    ]
