# Generated by Django 3.2.6 on 2022-12-26 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_auto_20221226_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='site_name',
            field=models.CharField(default='Krafta', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 26, 16, 0, 32, 915634)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 26, 16, 0, 32, 919538)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 26, 16, 0, 32, 914658)),
        ),
    ]
