# Generated by Django 3.2.6 on 2022-12-26 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_auto_20221226_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='site_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 26, 16, 19, 7, 244064)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 26, 16, 19, 7, 247915)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 26, 16, 19, 7, 242059)),
        ),
    ]
