# Generated by Django 5.0.2 on 2024-02-29 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_alter_order_start_date_alter_payment_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 29, 12, 22, 11, 328214)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 29, 12, 22, 11, 344807)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 29, 12, 22, 11, 327239)),
        ),
    ]
